### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by cwmke** [gustavomondron/twik#8]
I'm very interested in trying this out but I'm a firefox user.  Are there any plans to support firefox on the desktop?  Thanks.

**Comment by murderered** [comment]
Greizgh already wrote a plugin:
[https://addons.mozilla.org/de/firefox/addon/phashword/?src=search]
Go, and thank him :D

**Comment by cwmke** [comment]
Perfect!  Thanks a lot.
